spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082
