package com.agentbanking.common.audit;

public enum AuditEventType {
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_LOCKED, USER_UNLOCKED,
    PASSWORD_RESET, LOGIN_SUCCESS, LOGIN_FAILURE,
    AGENT_CREATED, AGENT_UPDATED, AGENT_DEACTIVATED,
    KYC_SUBMITTED, KYC_APPROVED, KYC_REJECTED,
    TRANSACTION_CREATED, TRANSACTION_COMPLETED, TRANSACTION_FAILED, TRANSACTION_REVERSED,
    FLOAT_DEPOSIT, FLOAT_WITHDRAWAL,
    SETTLEMENT_INITIATED, SETTLEMENT_COMPLETED,
    RULE_UPDATED, LIMIT_CHANGED,
    BILL_PAYMENT_INITIATED, BILL_PAYMENT_COMPLETED,
    PIN_PURCHASE_INITIATED, PIN_PURCHASE_COMPLETED,
    SAGA_STARTED, SAGA_COMPLETED, SAGA_ROLLED_BACK,
    PERMISSION_GRANTED, PERMISSION_REVOKED,
    ROLE_CREATED, ROLE_UPDATED, ROLE_DELETED
}
